// Generated from MochiKernelShaders.ptx
#pragma once

const char MochiKernel_ptx[] = R"(
//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-35813241
// Cuda compilation tools, release 12.9, V12.9.41
// Based on NVVM 7.0.1
//

.version 8.8
.target sm_86
.address_size 64

	// .globl	__raygen__shootEdgeRays
.extern .func  (.param .b32 func_retval0) vprintf
(
	.param .b64 vprintf_param_0,
	.param .b64 vprintf_param_1
)
;
.const .align 8 .b8 params[64];
.global .align 1 .b8 $str[28] = {67, 111, 108, 108, 105, 115, 105, 111, 110, 32, 98, 117, 102, 102, 101, 114, 32, 111, 118, 101, 114, 102, 108, 111, 119, 33, 10};
.global .align 1 .b8 $str$1[51] = {65, 72, 32, 69, 114, 114, 111, 114, 58, 32, 72, 105, 116, 32, 65, 117, 120, 32, 83, 66, 84, 32, 98, 117, 116, 32, 80, 114, 105, 109, 73, 100, 120, 32, 37, 117, 32, 60, 32, 110, 117, 109, 79, 114, 105, 103, 32, 37, 117, 10};
.global .align 1 .b8 $str$2[55] = {65, 72, 32, 69, 114, 114, 111, 114, 58, 32, 77, 105, 115, 115, 105, 110, 103, 32, 118, 101, 114, 116, 101, 120, 47, 105, 110, 100, 101, 120, 32, 100, 97, 116, 97, 32, 102, 111, 114, 32, 97, 117, 120, 32, 104, 105, 116, 32, 99, 104, 101, 99, 107, 10};
.global .align 1 .b8 $str$3[37] = {65, 72, 32, 69, 114, 114, 111, 114, 58, 32, 85, 110, 107, 110, 111, 119, 110, 32, 83, 66, 84, 32, 103, 101, 111, 109, 101, 116, 114, 121, 32, 116, 121, 112, 101, 10};

.visible .entry __raygen__shootEdgeRays()
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<45>;
	.reg .b32 	%r<80>;
	.reg .b64 	%rd<14>;


	// begin inline asm
	call (%r3), _optix_get_launch_index_x, ();
	// end inline asm
	// begin inline asm
	call (%r4), _optix_get_launch_index_y, ();
	// end inline asm
	ld.const.u32 	%r5, [params+40];
	setp.ge.u32 	%p1, %r3, %r5;
	@%p1 bra 	$L__BB0_9;

	ld.const.u64 	%rd1, [params+32];
	cvta.to.global.u64 	%rd2, %rd1;
	mul.wide.u32 	%rd3, %r3, 12;
	add.s64 	%rd4, %rd2, %rd3;
	ld.const.u64 	%rd5, [params+24];
	cvta.to.global.u64 	%rd6, %rd5;
	ld.global.u32 	%r6, [%rd4];
	mul.wide.s32 	%rd7, %r6, 12;
	add.s64 	%rd8, %rd6, %rd7;
	ld.global.f32 	%f1, [%rd8];
	ld.global.f32 	%f2, [%rd8+4];
	ld.global.f32 	%f3, [%rd8+8];
	ld.global.u32 	%r7, [%rd4+4];
	mul.wide.s32 	%rd9, %r7, 12;
	add.s64 	%rd10, %rd6, %rd9;
	ld.global.f32 	%f4, [%rd10];
	ld.global.f32 	%f5, [%rd10+4];
	ld.global.f32 	%f6, [%rd10+8];
	ld.global.u32 	%r8, [%rd4+8];
	mul.wide.s32 	%rd11, %r8, 12;
	add.s64 	%rd12, %rd6, %rd11;
	ld.global.f32 	%f40, [%rd12];
	ld.global.f32 	%f39, [%rd12+4];
	ld.global.f32 	%f44, [%rd12+8];
	setp.eq.s32 	%p2, %r4, 0;
	@%p2 bra 	$L__BB0_6;

	setp.eq.s32 	%p3, %r4, 1;
	@%p3 bra 	$L__BB0_5;

	setp.ne.s32 	%p4, %r4, 2;
	@%p4 bra 	$L__BB0_9;

	sub.ftz.f32 	%f43, %f1, %f40;
	sub.ftz.f32 	%f42, %f2, %f39;
	sub.ftz.f32 	%f41, %f3, %f44;
	bra.uni 	$L__BB0_7;

$L__BB0_6:
	sub.ftz.f32 	%f43, %f4, %f1;
	sub.ftz.f32 	%f42, %f5, %f2;
	sub.ftz.f32 	%f41, %f6, %f3;
	mov.f32 	%f39, %f2;
	mov.f32 	%f40, %f1;
	mov.f32 	%f44, %f3;
	bra.uni 	$L__BB0_7;

$L__BB0_5:
	sub.ftz.f32 	%f43, %f40, %f4;
	sub.ftz.f32 	%f42, %f39, %f5;
	sub.ftz.f32 	%f41, %f44, %f6;
	mov.f32 	%f39, %f5;
	mov.f32 	%f40, %f4;
	mov.f32 	%f44, %f6;

$L__BB0_7:
	mul.ftz.f32 	%f26, %f43, %f43;
	fma.rn.ftz.f32 	%f27, %f42, %f42, %f26;
	fma.rn.ftz.f32 	%f28, %f41, %f41, %f27;
	sqrt.approx.ftz.f32 	%f25, %f28;
	setp.lt.ftz.f32 	%p5, %f25, 0f3727C5AC;
	@%p5 bra 	$L__BB0_9;

	rcp.approx.ftz.f32 	%f38, %f25;
	mul.ftz.f32 	%f32, %f43, %f38;
	mul.ftz.f32 	%f33, %f42, %f38;
	mul.ftz.f32 	%f34, %f41, %f38;
	ld.const.u64 	%rd13, [params];
	add.ftz.f32 	%f36, %f25, 0fB727C5AC;
	mov.f32 	%f37, 0f00000000;
	mov.u32 	%r45, 2;
	mov.u32 	%r47, 1;
	mov.u32 	%r79, 0;
	// begin inline asm
	call(%r9,%r10,%r11,%r12,%r13,%r14,%r15,%r16,%r17,%r18,%r19,%r20,%r21,%r22,%r23,%r24,%r25,%r26,%r27,%r28,%r29,%r30,%r31,%r32,%r33,%r34,%r35,%r36,%r37,%r38,%r39,%r40),_optix_trace_typed_32,(%r79,%rd13,%f40,%f39,%f44,%f32,%f33,%f34,%f37,%f36,%f37,%r47,%r79,%r79,%r45,%r79,%r47,%r3,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79,%r79);
	// end inline asm

$L__BB0_9:
	ret;

}
	// .globl	__anyhit__processHit
.visible .entry __anyhit__processHit()
{
	.local .align 8 .b8 	__local_depot1[8];
	.reg .b64 	%SP;
	.reg .b64 	%SPL;
	.reg .pred 	%p<24>;
	.reg .b16 	%rs<5>;
	.reg .f32 	%f<60>;
	.reg .b32 	%r<35>;
	.reg .b64 	%rd<47>;


	mov.u64 	%SPL, __local_depot1;
	cvta.local.u64 	%SP, %SPL;
	// begin inline asm
	call (%rd6), _optix_get_sbt_data_ptr_64, ();
	// end inline asm
	// begin inline asm
	call (%r12), _optix_read_primitive_idx, ();
	// end inline asm
	mov.u32 	%r14, 0;
	// begin inline asm
	call (%r13), _optix_get_payload, (%r14);
	// end inline asm
	ld.u32 	%r15, [%rd6+32];
	setp.eq.s32 	%p1, %r15, 0;
	@%p1 bra 	$L__BB1_22;

	setp.ne.s32 	%p2, %r15, 1;
	@%p2 bra 	$L__BB1_28;

	ld.u32 	%r3, [%rd6+64];
	setp.lt.u32 	%p3, %r12, %r3;
	@%p3 bra 	$L__BB1_21;
	bra.uni 	$L__BB1_3;

$L__BB1_21:
	add.u64 	%rd31, %SP, 0;
	add.u64 	%rd32, %SPL, 0;
	st.local.v2.u32 	[%rd32], {%r12, %r3};
	mov.u64 	%rd33, $str$1;
	cvta.global.u64 	%rd34, %rd33;
	{ // callseq 2, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd34;
	.param .b64 param1;
	st.param.b64 	[param1+0], %rd31;
	.param .b32 retval0;
	call.uni (retval0), 
	vprintf, 
	(
	param0, 
	param1
	);
	ld.param.b32 	%r27, [retval0+0];
	} // callseq 2
	bra.uni 	$L__BB1_29;

$L__BB1_22:
	ld.u64 	%rd5, [%rd6+56];
	setp.eq.s64 	%p19, %rd5, 0;
	mov.u32 	%r34, -1;
	@%p19 bra 	$L__BB1_24;

	mul.wide.u32 	%rd35, %r12, 4;
	add.s64 	%rd36, %rd5, %rd35;
	ld.u32 	%r34, [%rd36];

$L__BB1_24:
	ld.const.u8 	%rs4, [params+56];
	setp.ne.s16 	%p20, %rs4, 0;
	setp.eq.s32 	%p21, %r13, %r12;
	and.pred  	%p22, %p21, %p20;
	@%p22 bra 	$L__BB1_29;

	ld.const.u64 	%rd37, [params+16];
	cvta.to.global.u64 	%rd38, %rd37;
	atom.global.add.u32 	%r11, [%rd38], 1;
	ld.const.u32 	%r29, [params+60];
	setp.lt.u32 	%p23, %r11, %r29;
	@%p23 bra 	$L__BB1_27;
	bra.uni 	$L__BB1_26;

$L__BB1_27:
	ld.const.u64 	%rd41, [params+8];
	cvta.to.global.u64 	%rd42, %rd41;
	mul.wide.u32 	%rd43, %r11, 16;
	add.s64 	%rd44, %rd42, %rd43;
	st.global.u32 	[%rd44], %r13;
	mov.u32 	%r31, -1;
	st.global.u32 	[%rd44+8], %r31;
	st.global.u32 	[%rd44+4], %r12;
	st.global.u32 	[%rd44+12], %r34;
	bra.uni 	$L__BB1_29;

$L__BB1_28:
	mov.u64 	%rd45, $str$3;
	cvta.global.u64 	%rd46, %rd45;
	{ // callseq 4, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd46;
	.param .b64 param1;
	st.param.b64 	[param1+0], 0;
	.param .b32 retval0;
	call.uni (retval0), 
	vprintf, 
	(
	param0, 
	param1
	);
	ld.param.b32 	%r32, [retval0+0];
	} // callseq 4

$L__BB1_29:
	ret;

$L__BB1_3:
	sub.s32 	%r4, %r12, %r3;
	mul.wide.u32 	%rd7, %r4, -1431655765;
	shr.u64 	%rd8, %rd7, 33;
	cvt.u32.u64 	%r5, %rd8;
	ld.u64 	%rd2, [%rd6+56];
	setp.eq.s64 	%p4, %rd2, 0;
	mov.u32 	%r33, -1;
	@%p4 bra 	$L__BB1_5;

	mul.wide.u32 	%rd9, %r5, 4;
	add.s64 	%rd10, %rd2, %rd9;
	ld.u32 	%r33, [%rd10];

$L__BB1_5:
	ld.const.u8 	%rs1, [params+56];
	setp.ne.s16 	%p5, %rs1, 0;
	setp.eq.s32 	%p6, %r13, %r5;
	and.pred  	%p7, %p6, %p5;
	@%p7 bra 	$L__BB1_29;

	ld.u64 	%rd3, [%rd6+48];
	setp.eq.s64 	%p8, %rd3, 0;
	@%p8 bra 	$L__BB1_20;

	ld.u64 	%rd4, [%rd6+40];
	setp.eq.s64 	%p9, %rd4, 0;
	@%p9 bra 	$L__BB1_20;

	mul.wide.u32 	%rd11, %r5, 12;
	add.s64 	%rd12, %rd3, %rd11;
	ld.u32 	%r17, [%rd12];
	mul.wide.s32 	%rd13, %r17, 12;
	add.s64 	%rd14, %rd4, %rd13;
	ld.f32 	%f56, [%rd14];
	ld.f32 	%f57, [%rd14+4];
	ld.f32 	%f58, [%rd14+8];
	ld.u32 	%r18, [%rd12+4];
	mul.wide.s32 	%rd15, %r18, 12;
	add.s64 	%rd16, %rd4, %rd15;
	ld.f32 	%f4, [%rd16];
	ld.f32 	%f5, [%rd16+4];
	ld.f32 	%f6, [%rd16+8];
	ld.u32 	%r19, [%rd12+8];
	mul.wide.s32 	%rd17, %r19, 12;
	add.s64 	%rd18, %rd4, %rd17;
	ld.f32 	%f7, [%rd18];
	ld.f32 	%f8, [%rd18+4];
	ld.f32 	%f9, [%rd18+8];
	mul.lo.s32 	%r21, %r5, 3;
	sub.s32 	%r22, %r4, %r21;
	cvt.u16.u32 	%rs2, %r22;
	and.b16  	%rs3, %rs2, 255;
	setp.eq.s16 	%p10, %rs3, 0;
	mov.f32 	%f53, %f4;
	mov.f32 	%f54, %f5;
	mov.f32 	%f55, %f6;
	@%p10 bra 	$L__BB1_12;

	setp.eq.s16 	%p11, %rs2, 1;
	@%p11 bra 	$L__BB1_11;

	setp.ne.s16 	%p12, %rs2, 2;
	mov.f32 	%f53, %f56;
	mov.f32 	%f54, %f57;
	mov.f32 	%f55, %f58;
	mov.f32 	%f56, %f7;
	mov.f32 	%f57, %f8;
	mov.f32 	%f58, %f9;
	@%p12 bra 	$L__BB1_29;
	bra.uni 	$L__BB1_12;

$L__BB1_26:
	mov.u64 	%rd39, $str;
	cvta.global.u64 	%rd40, %rd39;
	{ // callseq 3, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd40;
	.param .b64 param1;
	st.param.b64 	[param1+0], 0;
	.param .b32 retval0;
	call.uni (retval0), 
	vprintf, 
	(
	param0, 
	param1
	);
	ld.param.b32 	%r30, [retval0+0];
	} // callseq 3
	bra.uni 	$L__BB1_29;

$L__BB1_20:
	mov.u64 	%rd29, $str$2;
	cvta.global.u64 	%rd30, %rd29;
	{ // callseq 1, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd30;
	.param .b64 param1;
	st.param.b64 	[param1+0], 0;
	.param .b32 retval0;
	call.uni (retval0), 
	vprintf, 
	(
	param0, 
	param1
	);
	ld.param.b32 	%r26, [retval0+0];
	} // callseq 1
	bra.uni 	$L__BB1_29;

$L__BB1_11:
	mov.f32 	%f53, %f7;
	mov.f32 	%f54, %f8;
	mov.f32 	%f55, %f9;
	mov.f32 	%f56, %f4;
	mov.f32 	%f57, %f5;
	mov.f32 	%f58, %f6;

$L__BB1_12:
	// begin inline asm
	call (%f27), _optix_get_ray_tmax, ();
	// end inline asm
	// begin inline asm
	call (%f28), _optix_get_world_ray_origin_x, ();
	// end inline asm
	// begin inline asm
	call (%f29), _optix_get_world_ray_origin_y, ();
	// end inline asm
	// begin inline asm
	call (%f30), _optix_get_world_ray_origin_z, ();
	// end inline asm
	// begin inline asm
	call (%f31), _optix_get_world_ray_direction_x, ();
	// end inline asm
	// begin inline asm
	call (%f32), _optix_get_world_ray_direction_y, ();
	// end inline asm
	// begin inline asm
	call (%f33), _optix_get_world_ray_direction_z, ();
	// end inline asm
	fma.rn.ftz.f32 	%f34, %f27, %f31, %f28;
	fma.rn.ftz.f32 	%f35, %f27, %f32, %f29;
	fma.rn.ftz.f32 	%f36, %f27, %f33, %f30;
	sub.ftz.f32 	%f16, %f34, %f56;
	sub.ftz.f32 	%f17, %f35, %f57;
	sub.ftz.f32 	%f18, %f36, %f58;
	sub.ftz.f32 	%f19, %f53, %f56;
	sub.ftz.f32 	%f20, %f54, %f57;
	mul.ftz.f32 	%f37, %f20, %f20;
	fma.rn.ftz.f32 	%f38, %f19, %f19, %f37;
	sub.ftz.f32 	%f21, %f55, %f58;
	fma.rn.ftz.f32 	%f22, %f21, %f21, %f38;
	setp.lt.ftz.f32 	%p13, %f22, 0f2EDBE6FE;
	@%p13 bra 	$L__BB1_15;
	bra.uni 	$L__BB1_13;

$L__BB1_15:
	mul.ftz.f32 	%f51, %f17, %f17;
	fma.rn.ftz.f32 	%f52, %f16, %f16, %f51;
	fma.rn.ftz.f32 	%f59, %f18, %f18, %f52;
	bra.uni 	$L__BB1_16;

$L__BB1_13:
	mul.ftz.f32 	%f39, %f20, %f17;
	fma.rn.ftz.f32 	%f40, %f19, %f16, %f39;
	fma.rn.ftz.f32 	%f23, %f21, %f18, %f40;
	setp.lt.ftz.f32 	%p14, %f23, 0fB727C5AC;
	add.ftz.f32 	%f41, %f22, 0f3727C5AC;
	setp.gt.ftz.f32 	%p15, %f23, %f41;
	or.pred  	%p16, %p14, %p15;
	@%p16 bra 	$L__BB1_29;

	div.approx.ftz.f32 	%f42, %f23, %f22;
	mul.ftz.f32 	%f43, %f19, %f42;
	mul.ftz.f32 	%f44, %f20, %f42;
	mul.ftz.f32 	%f45, %f21, %f42;
	sub.ftz.f32 	%f46, %f16, %f43;
	sub.ftz.f32 	%f47, %f17, %f44;
	sub.ftz.f32 	%f48, %f18, %f45;
	mul.ftz.f32 	%f49, %f47, %f47;
	fma.rn.ftz.f32 	%f50, %f46, %f46, %f49;
	fma.rn.ftz.f32 	%f59, %f48, %f48, %f50;

$L__BB1_16:
	setp.geu.ftz.f32 	%p17, %f59, 0f2EDBE6FE;
	@%p17 bra 	$L__BB1_29;

	ld.const.u64 	%rd21, [params+16];
	cvta.to.global.u64 	%rd22, %rd21;
	atom.global.add.u32 	%r8, [%rd22], 1;
	ld.const.u32 	%r23, [params+60];
	setp.lt.u32 	%p18, %r8, %r23;
	@%p18 bra 	$L__BB1_19;
	bra.uni 	$L__BB1_18;

$L__BB1_19:
	ld.const.u64 	%rd25, [params+8];
	cvta.to.global.u64 	%rd26, %rd25;
	mul.wide.u32 	%rd27, %r8, 16;
	add.s64 	%rd28, %rd26, %rd27;
	st.global.u32 	[%rd28], %r13;
	mov.u32 	%r25, -1;
	st.global.u32 	[%rd28+8], %r25;
	st.global.u32 	[%rd28+4], %r5;
	st.global.u32 	[%rd28+12], %r33;
	bra.uni 	$L__BB1_29;

$L__BB1_18:
	mov.u64 	%rd23, $str;
	cvta.global.u64 	%rd24, %rd23;
	{ // callseq 0, 0
	.reg .b32 temp_param_reg;
	.param .b64 param0;
	st.param.b64 	[param0+0], %rd24;
	.param .b64 param1;
	st.param.b64 	[param1+0], 0;
	.param .b32 retval0;
	call.uni (retval0), 
	vprintf, 
	(
	param0, 
	param1
	);
	ld.param.b32 	%r24, [retval0+0];
	} // callseq 0
	bra.uni 	$L__BB1_29;

}
	// .globl	__miss__miss
.visible .entry __miss__miss()
{



	ret;

}


)";
